version: '2.2'
services:
  base:
    build:
      context: .
    image: chord:v1
    command:
      - "bash"
  centralnode:
    image: chord:v1
    environment:
      - CHORD_NODE_TYPE=central
      - NODE_ID=24
    ports:
      - 11211:11211
    networks:
      - chord_network
networks:
  chord_network:
    name: chord_network
