version: '2.2'
services:
  base:
    build:
      context: .
    image: chord:v1
    command:
      - "bash"
  centralnode:
    image: chord:v1
    environment:
      - CHORD_NODE_TYPE=central
      - NODE_ID=24
    ports:
      - 11211:11211
  regular01:
    image: chord:v1
    environment:
      - CHORD_NODE_TYPE=regular
      - CHORD_CENTRAL_NODE=centralnode
      - CHORD_CENTRAL_NODE_PORT=25520
      - NODE_ID=34
    depends_on:
      - centralnode
  regular02:
    image: chord:v1
    environment:
      - CHORD_NODE_TYPE=regular
      - CHORD_CENTRAL_NODE=centralnode
      - CHORD_CENTRAL_NODE_PORT=25520
      - NODE_ID=36
  regular03:
    image: chord:v1
    environment:
      - CHORD_NODE_TYPE=regular
      - CHORD_CENTRAL_NODE=centralnode
      - CHORD_CENTRAL_NODE_PORT=25520
      - NODE_ID=99
    depends_on:
      - centralnode
