version: '2.2'
services:
  base:
    build:
      context: .
    image: chord:v1
    command:
      - "bash"
  centralnode:
    image: chord:v1
    environment:
      - CHORD_NODE_TYPE=central
      - NODE_ID=24
    ports:
      - 11211:11211
    networks:
      - chord_network
  shell:
    image: busybox
    networks:
      - chord_network
  benchmark:
      image: redislabs/memtier_benchmark
      networks:
        - chord_network
      command: "echo 'run via shell'"
networks:
  chord_network:
    name: chord_network
